###
DELETE http://localhost:3001/api/notes/1
Content-Type: application/json

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "This is the content of the note.",
  "important": true
}

###
GET localhost:3001/api/notes

